<?php

function dna_menu() {
    $items['dna'] = array(
        'title' => 'DNA',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_success'] = array(
        'title' => 'DNA Results',
        'page callback' => 'dna_form_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['dna'] = array(
        '#title' => 'User DNA Sequence',
        '#type' => 'textfield',
        '#description' => t('Enter DNA sequence to be copied.'),
        '#element_validate' => array('element_validate_dna'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => '{ Sequence }',
    );
    return $form;
}

function element_validate_dna($element) {
    $pairs = array('A' => 'T', 'T' => 'A', 'C' => 'G', 'G' => 'C');

    if ( ! array_key_exists($element['#value'], $pairs)) {
        form_error($element, t('Please enter a valid nucleotide: G, A, T, or C'));
    }
}

function dna_pcr($dna) {
    $pairs = array('A' => 'T', 'T' => 'A', 'C' => 'G', 'G' => 'C');
    $output = '';
    $dna = strtoupper($dna);
    $dna = str_split($dna);

    foreach ($dna as $nucleotide) {
        $output .= $pairs[$nucleotide];
    }

    return $output;
}

function dna_form_submit($form, &$form_state) {
    $_SESSION['output'] = dna_pcr($form_state['values']['dna']);
    $form_state['redirect'] = 'dna_success';
}

function dna_form_success() {
    return $_SESSION['output'];
}
